---
abstract: 'ArangoDB client for Perl.'
author:
  - 'Hideaki Ohno <hide.o.j55 {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ArangoDB
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Data::Clone: 0
requires:
  Carp: 0
  Class::Accessor::Lite: 0
  Data::Util: 0
  Furl: 0
  JSON: 0
  List::MoreUtils: 0
  MIME::Base64: 0
  Scalar::Util: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hideo55/p5-ArangoDB.git
version: 0.01_02
